language: ruby
sudo: required
rvm:
  - 2.4.2
before_install:
  - gem update --system --no-doc # https://github.com/sickill/rainbow/issues/49
install:
  - bundle install
  - bundle exec berks install
script:
  - bundle exec rake
